name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send ping to backend
        run: curl -s https://coursegpt-backend.onrender.com/api/ping
